### ISSUE TITLE
Adding LICENSE section in README

### ISSUE THREAD

**Issue by the-amazing-atharva** [petermatts/nfl-season-predictor#35]
Regarding issue #33 

Hey!!

I found this issue while surfing GitHub and would suggest adding a license section in the README as follows : 
If you liked my suggestion do let me know so that I can send you a pull request to save your time 

![image](https://user-images.githubusercontent.com/121221252/214743866-1758e9eb-362b-4088-919a-643ad5244d3c.png)

**Comment by petermatts** [comment]
Thank you for the suggestion, I had actually already made these changes but forgot to commit.
Thank you again.

**Comment by the-amazing-atharva** [comment]
No worries!
